service: rankly-lambda

frameworkVersion: ">=1.1.0"

custom:
  bucket: rankly-bucket-123456789

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"

functions:
  save:
    handler: handler.save
    environment:
      BUCKET: ${self:custom.bucket}
