version: '3.6'
#192.168.100.99
services:

  # Backend API
  smart-brain-api: 
    container_name: backend
    build: ./
    command: npm start
    working_dir: /usr/src/smart-brain-api
    environment:
      POSTGRES_URI: postgres://sally:secret@postgres:5432/smart-brain-docker
    ports:
      - "3000:3000"
    volumes:
      - //Dev/Udemy/UdemyJ2SWebDeveloper/Docker/smart-brain-api:/usr/src/smart-brain-api
  
  # Postgres
  postgres:
    environment:
      POSTGRES_USER: sally
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: smart-brain-docker
      POSTGRES_HOST: postgres
    build: ./postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
volumes:
  db-data:
  
